### PR TITLE
:jp: Update README-ja.adoc

### PR DESCRIPTION
**Pull request by naru0504**
@hinaloe 作りなおしました！不手際がありご迷惑おかけしました。

### CODE REVIEW

**Comment by hinaloe** [comment]
(renewal of #277)
:+1:

(実は私はWriteAccessは持ってないんです……I'm not allowed write Access)


cc, @anthonny

**Comment by naru0504** [comment]
@hinaloe Anyway, Thanks a lot!!

Hello @anthonny 
Nice to meet you. I tried to update README-ja.adoc.
I think there is no mistake in it. If I find any mistake, I'm willing to fix it asap!
Please merge this pr.

Regards.

**Comment by jaredmorgs** [comment]
I'll merge it and if another community member identifies a change we can fix it.

**Comment by naru0504** [comment]
Thanks.

**Pull request merged**
