### PR TITLE
Resolves #342, remove empty tags

### LINKED ISSUE #342: Error when publishing a new post with an extra comma at the end of hp-tags attribute
### Steps to reproduce

 1.Create a new blog post with the following content

```
= Bug
:hp-tags: test,
```

 2.Save and publish the blog post

```
POST https://api.github.com/repos/indusbox/indusbox.github.io/git/trees?1458430101792 422 (Unprocessable Entity)

PostsServices - publishElements error Object {path: "/repos/indusbox/indusbox.github.io/git/trees", request: XMLHttpRequest, error: 422}
  (anonymous function) @ app.js?version=0.4.0-1454500827630:68
  o @ app.js?version=0.4.0-1454500827630:26
  c @ app.js?version=0.4.0-1454500827630:26u @ app.js?version=0.4.0-1454500827630:26
  (anonymous function) @ app.js?version=0.4.0-1454500827630:26
  (anonymous function) @ app.js?version=0.4.0-1454500827630:26
  o @ app.js?version=0.4.0-1454500827630:26
  c @ app.js?version=0.4.0-1454500827630:26
  u @ app.js?version=0.4.0-1454500827630:26
  (anonymous function) @ app.js?version=0.4.0-1454500827630:26
  (anonymous function) @ app.js?version=0.4.0-1454500827630:26
  s @ app.js?version=0.4.0-1454500827630:52
  (anonymous function) @ app.js?version=0.4.0-1454500827630:52
  T.m.when @ app.js?version=0.4.0-1454500827630:52
  r.promiseDispatch @ app.js?version=0.4.0-1454500827630:52
  (anonymous function) @ app.js?version=0.4.0-1454500827630:52
  n @ app.js?version=0.4.0-1454500827630:52
  t @ app.js?version=0.4.0-1454500827630:52
```

Error message from the GitHub API is:
```json
{
  "message": "tree.path contains a malformed path component",
  "documentation_url": "https://developer.github.com/v3/git/trees/#create-a-tree"
}
```

### PR DESCRIPTION
**Pull request by Mogztter**

### CODE REVIEW

**Comment by jaredmorgs** [comment]
Nice one @Mogztter !

I'll get @anthonny to merge this on dev.HubPress.io

**Comment by Mogztter** [comment]
Ok cool :+1:

**Comment by Mogztter** [comment]
I think we can close this issue ?

**Comment by anthonny** [comment]
yes

**Comment by anthonny** [comment]
Thanks again

**Pull request closed without merging**
