### PR TITLE
Update README-ja.adoc

### PR DESCRIPTION
**Pull request by hinaloe**
as #138

### CODE REVIEW

**Comment by jaredmorgs** [comment]
Hi @hinaloe and thanks for the PR. Should I merge #138 or #140? Or should I merge incrementally?

**Comment by hinaloe** [comment]
both! (#138 is on master, #140 is on development)

**Comment by anthonny** [comment]
The best process IHMO, i to make PR on development, then we merge and report on gh-pages and master, wdyt?

**Comment by jaredmorgs** [comment]
ACK @anthonny 

I'll also make changes on /development as well for any docs changes I do.

**Comment by jaredmorgs** [comment]
@hinaloe I'll merge the #140 PR as this one is on /development. Thanks again for your work on ja-JP translations.

**Pull request merged**
