### PR TITLE
Added two-factor auth

### PR DESCRIPTION
**Pull request by enjikaka**
Created an input box for the temp 6-digit token so users with two-factor auth can log in.

I do not think this will work with SMS:es though, only if you use an app for tokens. (Like Google Authenticator our Authy)

### CODE REVIEW

**Comment by alxndr** [comment]
Is TFA via SMS still unsupported?

**Comment by enjikaka** [comment]
Yep. I don't think it can be supported either. I tried.
Den 16 feb 2015 19:34 skrev "Alexander Quine" <notifications@github.com>:

**Comment by anthonny** [comment]
It should be good now, can you merge the upstream and test please ?

**Comment by anthonny** [comment]
I confirm :smile: it works

**Comment by enjikaka** [comment]
Awesome!
Den 16 feb 2015 20:28 skrev "Anthonny Quérouil" <notifications@github.com>:

**Comment by anthonny** [comment]
:beers:

**Comment by alxndr** [comment]
Works for me too, thanks!

FWIW merging master into my gh-pages branch gave 3 merge conflicts: `README.adoc`, `hubpress/scripts/app.js`, and `images/README.adoc`.

**Comment by anthonny** [comment]
ATM master and gh-pages are unsync
to update your gh-pages, you should merge from the upstream/gh-pages

**Comment by alxndr** [comment]
Trying to save a post or setting now fails, with a GET to [this](https://api.github.com/repos/NAME/REPO/git/refs/heads/gh-pages) showing up as a 401 in the Network tab. Here's the response:

    {
      documentation_url: "https://developer.github.com/v3/auth#working-with-two-factor-authentication"
      message: "Must specify two-factor authentication OTP code."
    }

**Comment by anthonny** [comment]
There's still à bug with auth, after loin just refresh your browser

**Comment by alxndr** [comment]
Refreshing after logging in hasn't seemed to change anything: still receiving the message "Publishing
An error has occurred, see your console for more informations."

**Comment by anthonny** [comment]
Can you show me the content you try to save ?

**Comment by alxndr** [comment]
Just entering "test" and trying to save or publish a post causes it. The console has lots of messages, but also two errors for loading Dexie.min.map.js and opal.js.map.

**Comment by anthonny** [comment]
You must add a title, title is the minimum requirement.

Try with: 

= my title

My content

**Comment by alxndr** [comment]
Aha, that's the ticket. Should work on the error messaging there.

How about on the settings page? I fill in a title and my Github account, hit Submit at the bottom, and it shows a "Settings save" error message (plus one about publishing).

It's apparently not saving my session too; it requires me to log in each time.

**Pull request closed without merging**
